### PR TITLE
feat: updating all packages to new versions

### PR DESCRIPTION
**Pull request by Cadienvan**

### CODE REVIEW

**Comment by Cadienvan** [comment]
@mateonunez I had some free time and decided to bump everything, you agree?

**Comment by Cadienvan** [comment]
I don't get what is going on with the tests.

**Comment by mateonunez** [comment]
Unfortunately tap is changing license and many other things.... I suggest to keep v16 trying to migrate to Node Test Runners as soon as possible. I have already done this work with `async-cache-dedupe` and `Platformatic`, it is not that difficult.

**Comment by Cadienvan** [comment]
Ok I guess we'll close it for now then!

**Pull request closed without merging**
